# Generated by Django 4.1.1 on 2022-09-14 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, upload_to='projects/images'),
        ),
    ]
