# Generated by Django 4.1.1 on 2022-09-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_end_project_start_project_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/images'),
        ),
    ]
