# Generated by Django 4.1.1 on 2022-09-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(null=True, upload_to='projects/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(null=True, upload_to='projects/images'),
        ),
    ]
