# Generated by Django 4.1.1 on 2022-09-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_image_project_image1_project_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
    ]
