# Generated by Django 3.1.1 on 2022-09-26 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0016_commentsreport_donation_projectsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ManyToManyField(related_name='report_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentsreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_report', to='projects.comment'),
        ),
    ]
