# Generated by Django 3.1.1 on 2022-09-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220926_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='report',
        ),
    ]
