# Generated by Django 3.1.1 on 2022-09-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220923_0426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
